# Generated by Django 4.2.1 on 2023-08-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('monthly_subcription_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payement_gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
                ('api_key', models.CharField(max_length=255)),
                ('api_client', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='confirm_password',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='payement_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message_template', models.CharField(max_length=12000)),
                ('method', models.CharField(max_length=255)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client')),
            ],
        ),
    ]
