# Generated by Django 4.2.4 on 2023-08-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_package_payement_gateway_client_confirm_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.IntegerField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=255)),
                ('api_client', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='payement_invoice',
            new_name='payment_invoice',
        ),
        migrations.DeleteModel(
            name='payement_gateway',
        ),
    ]
