# Generated by Django 4.2.4 on 2023-08-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_router_router_hotspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_sms_campain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('add_contact', models.IntegerField(blank=True, null=True)),
                ('upload_contact', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='register_sms_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('api_client', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='register_email_module',
            fields=[
                ('register_sms_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.register_sms_module')),
            ],
            bases=('App.register_sms_module',),
        ),
        migrations.CreateModel(
            name='register_whatspp_module',
            fields=[
                ('register_sms_module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='App.register_sms_module')),
            ],
            bases=('App.register_sms_module',),
        ),
    ]
