# Generated by Django 4.2.4 on 2023-08-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_register_sms_campain_register_sms_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_contact', models.IntegerField(blank=True, null=True)),
                ('upload_contact_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='register_campain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('add_contact', models.IntegerField(blank=True, null=True)),
                ('upload_contact', models.FileField(upload_to='')),
                ('message_template', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='register_sms_campain',
        ),
    ]
