# Generated by Django 4.2.4 on 2023-08-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_contacts_register_campain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
