# Generated by Django 4.2.1 on 2023-08-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_address_coupon_item_order_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='ip_adressv4',
            field=models.GenericIPAddressField(),
        ),
    ]
