# Generated by Django 4.2.1 on 2023-08-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_router_ip_adressv4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='packageItem',
        ),
        migrations.DeleteModel(
            name='package',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.client'),
        ),
        migrations.AlterField(
            model_name='router_hotspot',
            name='ip_adressv4',
            field=models.GenericIPAddressField(),
        ),
    ]
