# Generated by Django 4.2.1 on 2023-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_rename_item_packageitem_delete_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='packageItem',
            new_name='ProductItem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
