# Generated by Django 4.2.1 on 2023-08-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.payment_gateway'),
        ),
    ]
