# Generated by Django 4.2.1 on 2023-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_remove_client_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='upload_contact_file',
            field=models.IntegerField(),
        ),
    ]
