# Generated by Django 4.2.1 on 2023-08-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_contacts_upload_contact_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_campain',
            new_name='register_campaign',
        ),
    ]
