# Generated by Django 4.2.1 on 2023-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_register_campain_register_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('api_client', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='whatspp_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('api_client', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='register_campaign',
            new_name='campaign',
        ),
        migrations.RenameModel(
            old_name='register_sms_module',
            new_name='sms_module',
        ),
        migrations.RemoveField(
            model_name='register_whatspp_module',
            name='register_sms_module_ptr',
        ),
        migrations.DeleteModel(
            name='register_email_module',
        ),
        migrations.DeleteModel(
            name='register_whatspp_module',
        ),
    ]
